#!/usr/bin/env bash

# path to your virtualenv
source /home/mhrivnak/pythons/hometemp/bin/activate
# path to your django project
export PYTHONPATH=/home/mhrivnak/dev/tempgraph
export DJANGO_SETTINGS_MODULE=tempgraph.settings

python -m hometemp.fetch
